server.servlet.context-path: / # Context path of the application.
server.compression.enabled: true
server.compression.mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size: 1024
server.http2.enabled: true
server.port: ${SERVER_PORT:8080}

spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}
spring.main.allow-bean-definition-overriding: true # Enable bean override

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
# ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include: '*' # Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.exclude:  # Endpoint IDs that should be excluded or '*' for all.
management.endpoints.web.base-path: /management # Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
management.endpoints.web.path-mapping.health: healthcheck
# HEALTH ENDPOINT
management.endpoint.health.cache.time-to-live: 0ms # Maximum time that a response can be cached.
management.endpoint.health.access: unrestricted # Allows unrestricted access to the health endpoint
management.endpoint.health.roles:  # Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized.
management.endpoint.health.show-details: always # When to show full health details.
management.endpoint.health.show-components: always # When to show full health details.
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
# INFO CONTRIBUTORS (InfoContributorProperties)
management.info.build.enabled: true # Whether to enable build info.
management.info.defaults.enabled: true # Whether to enable default info contributors.
management.info.env.enabled: true # Whether to enable environment info.
management.info.git.enabled: true # Whether to enable git info.
management.info.git.mode: full # Mode to use to expose git information.

---
spring.config.activate.on-profile: local

# DATABASE
spring.datasource.h2.url: dbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.h2.driverClassName: org.h2.Driver
spring.datasource.h2.username: 'sa'
spring.h2.console.enabled: true
spring.h2.console.path: "/h2-console"

# JPA
spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: none
#spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.properties.hibernate:
  #dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  format_sql: true
  use_sql: true
  id.new_generator_mappings: false
  search.autoregister_listeners: false
  bytecode.use_reflection_optimizer: false

# FLYWAY
spring.flyway.enabled: true
spring.flyway.locations: classpath:/db/migration

# OPENAPI :: SPRINGDOC :: SWAGGER
springdoc:
  api-docs:
    groups.enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: alpha
    tags-sorter: alpha
