server.servlet.context-path: / # Context path of the application.
server.port: ${SERVER_PORT:8080} # Server HTTP port.
spring.application.name: '@project.artifactId@'
spring.application.version: '@project.version@'
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:local}
spring.main.allow-bean-definition-overriding: true # Enable bean override

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
# ENDPOINTS WEB CONFIGURATION
management.endpoints.web.exposure.include: '*' # Endpoint IDs that should be included or '*' for all.
management.endpoints.web.exposure.exclude:  # Endpoint IDs that should be excluded or '*' for all.
management.endpoints.web.base-path: /management # Base path for Web endpoints. Relative to server.servlet.context-path or management.server.servlet.context-path if management.server.port is configured.
management.endpoints.web.path-mapping.health: healthcheck
# HEALTH ENDPOINT
management.endpoint.health.cache.time-to-live: 0ms # Maximum time that a response can be cached.
management.endpoint.health.access: unrestricted # Allows unrestricted access to the health endpoint
management.endpoint.health.roles:  # Roles used to determine whether or not a user is authorized to be shown details. When empty, all authenticated users are authorized.
management.endpoint.health.show-details: always # When to show full health details.
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true
# INFO CONTRIBUTORS (InfoContributorProperties)
management.info.build.enabled: true # Whether to enable build info.
management.info.defaults.enabled: true # Whether to enable default info contributors.
management.info.env.enabled: true # Whether to enable environment info.
management.info.git.enabled: true # Whether to enable git info.
management.info.git.mode: full # Mode to use to expose git information.

---
spring.config.activate.on-profile: local

# Postgres
spring.datasource.postgres.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.postgres.jdbcUrl: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
spring.datasource.postgres.driver-class-name: org.postgresql.Driver
spring.datasource.postgres.username: postgres
spring.datasource.postgres.password: postgres
spring.datasource.testOnBorrow: true
spring.datasource.validationQuery: SELECT 1

# JPA specific configs
spring.jpa.open-in-view: false
#spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.properties.hibernate.show_sql: false
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.use_sql: true
spring.jpa.properties.hibernate.hibernate.dialect: true
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.search.autoregister_listeners: false
spring.jpa.properties.hibernate.bytecode.use_reflection_optimizer: false
#spring.jpa.properties.hibernate.default_schema: foo

spring.flyway.enabled: true
spring.flyway.locations: classpath:/db/migration
#spring.flyway.schemas: foo

# JaVers Configuration
javers.sqlSchemaManagementEnabled: true
javers.prettyPrint: true
javers.packagesToScan: com.cjrequena.sample.persistence.entity

javers:
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  packagesToScan:
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  usePrimitiveDefaults: true
  prettyPrintDateFormats:
    localDateTime: 'dd MMM yyyy, HH:mm:ss'
    zonedDateTime: 'dd MMM yyyy, HH:mm:ssZ'
    localDate: 'dd MMM yyyy'
    localTime: 'HH:mm:ss'
  sqlSchema:
  sqlSchemaManagementEnabled: true
  sqlGlobalIdCacheDisabled: false
  objectAccessHook: org.javers.hibernate.integration.HibernateUnproxyObjectAccessHook
  sqlGlobalIdTableName: jv_global_id
  sqlCommitTableName: jv_commit
  sqlSnapshotTableName: jv_snapshot
  sqlCommitPropertyTableName: jv_commit_property
  sqlGlobalIdSequenceName: jv_global_id_pk_seq
  sqlCommitSequenceName: jv_commit_pk_seq
  sqlSnapshotSequenceName: jv_snapshot_pk_seq
